name: Bug report
description: A bug happened!
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Mopsgamer
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: The bug...
    validations:
      required: true