name: Feature request
description: A feature needed!
title: "[Feature]: "
labels: ["feature"]
assignees:
  - Mopsgamer
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What?
      description: What would you like to see?
      placeholder: The idea...
    validations:
      required: true